# Generated by Django 5.2.5 on 2025-08-12 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sayadi_id', models.BigIntegerField(blank=True, null=True)),
                ('cheque_date', models.CharField(blank=True, max_length=20, null=True)),
                ('cheque_amount', models.BigIntegerField(blank=True, null=True)),
                ('holder', models.CharField(blank=True, max_length=100, null=True)),
                ('transfer_date', models.CharField(blank=True, max_length=20, null=True)),
                ('sayad_transfer', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'cheques',
            },
        ),
        migrations.CreateModel(
            name='CollateralType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('collateral_type', models.CharField(max_length=100)),
                ('collateral_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'collateral_types',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=20)),
                ('birth_date', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ChequeStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cheque_status', models.CharField(max_length=50)),
                ('inquiry_date', models.CharField(max_length=20)),
                ('cheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.cheque')),
            ],
            options={
                'db_table': 'cheque_statuses',
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('line_name', models.CharField(max_length=100)),
                ('beneficiary', models.BigIntegerField()),
                ('interest_rate', models.FloatField()),
                ('installment_count', models.IntegerField()),
                ('comission_fee', models.FloatField()),
                ('deposite_rate', models.FloatField()),
                ('leeway', models.IntegerField()),
                ('action1', models.CharField(blank=True, max_length=100, null=True)),
                ('action2', models.CharField(blank=True, max_length=100, null=True)),
                ('action3', models.CharField(blank=True, max_length=100, null=True)),
                ('action4', models.CharField(blank=True, max_length=100, null=True)),
                ('action5', models.CharField(blank=True, max_length=100, null=True)),
                ('action6', models.CharField(blank=True, max_length=100, null=True)),
                ('action7', models.CharField(blank=True, max_length=100, null=True)),
                ('action8', models.CharField(blank=True, max_length=100, null=True)),
                ('action9', models.CharField(blank=True, max_length=100, null=True)),
                ('action10', models.CharField(blank=True, max_length=100, null=True)),
                ('collateral_type1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_collateral1', to='apps.collateraltype')),
                ('collateral_type2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_collateral2', to='apps.collateraltype')),
                ('collateral_type3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_collateral3', to='apps.collateraltype')),
            ],
            options={
                'db_table': 'lines',
            },
        ),
        migrations.CreateModel(
            name='Guarantee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('guarantee_number', models.CharField(max_length=50)),
                ('issue_gregorian_date', models.CharField(blank=True, max_length=20, null=True)),
                ('issue_shamsi_date', models.CharField(max_length=20)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.line')),
            ],
            options={
                'db_table': 'guarantees',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('loan_number', models.CharField(max_length=50)),
                ('loan_amount', models.BigIntegerField()),
                ('issue_date', models.CharField(max_length=20)),
                ('comission_amount', models.BigIntegerField()),
                ('deposite_amount', models.BigIntegerField()),
                ('collateral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_collateral1', to='apps.cheque')),
                ('collateral2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_collateral2', to='apps.cheque')),
                ('collateral3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_collateral3', to='apps.cheque')),
                ('guarantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.guarantee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_user1', to='apps.user')),
                ('user2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_user2', to='apps.user')),
                ('user3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_user3', to='apps.user')),
            ],
            options={
                'db_table': 'loans',
            },
        ),
        migrations.AddField(
            model_name='cheque',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.loan'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.user'),
        ),
    ]
